extends: stylelint-config-recommended-scss
plugins:
  - stylelint-scss
  - stylelint-order
  - stylelint-csstree-validator
  - stylelint-selector-bem-pattern
rules:
  # 验证 CSS 的值是否匹配 W3C 标准和浏览器扩展
  csstree/validator: true


  # Color
  color-no-invalid-hex:
    - true
    - message: 禁止使用无效的十六进制颜色
  color-hex-case:
    - lower
    - message: 指定十六进制颜色为小写
  color-hex-length:
    - short
    - message: 指定十六进制颜色使用缩写

  # Font family
  font-family-no-duplicate-names:
    - true
    - message: 禁止出现重复字体
  font-family-no-missing-generic-family-keyword:
    - true
    - message: 字体名称中缺少通用字体
  font-weight-notation:
    - numeric
    - message: font-weight 值使终为数字

  # Function
  function-calc-no-invalid:
    - true
    - message: 确保 calc 函数表达式有效性
  function-calc-no-unspaced-operator:
    - true
    - message: 禁止在 calc 函数内使用不加空格的操作符
  function-linear-gradient-no-nonstandard-direction:
    - true
    - message: 禁止在 linear-gradient 中使用无效的方向值

  # Number
  number-leading-zero:
    - never
    - message: 前导不能是 0
  number-no-trailing-zeros:
    - true
    - message: 尾数不能带 0

  # String
  string-no-newline:
    - true
    - message: 非法换行
  string-quotes:
    - single
    - message: 字符串使用单引号

  # Length
  length-zero-no-unit:
    - true
    - message: 长度为 0 时，不用带单位

  # Unit
  unit-no-unknown:
    - true
    - message: 非法单位
  unit-case: lower
  value-keyword-case: lower

  # Property
  property-no-unknown:
    - true
    - message: 非法属性

  # Keyframe declaration
  keyframe-declaration-no-important:
    - true
    - message: 禁止在 Keyframe 声明中使用 !important

  # Declaration block
  declaration-block-no-duplicate-properties:
    - true
    - message: 禁止在同一声明块中出现重复的属性
  declaration-block-no-shorthand-property-overrides:
    - true
    - message: 禁止缩写属性覆盖相关普通写法属性

  # Block
  block-no-empty:
    - true
    - message: 禁止出现空块

  # Selector
  selector-pseudo-class-no-unknown:
    - true
    - message: 非法的伪类选择器
  selector-pseudo-element-no-unknown:
    - true
    - message: 非法的伪元素
  selector-type-no-unknown:
    - true
    - message: 非法的类型选择器

  # Media feature
  media-feature-name-no-unknown:
    - true
    - message: 非法的 media 特性名称

  # At-rule
  at-rule-no-unknown:
    - null

  # Comment
  comment-no-empty:
    - true
    - message: 禁止空注释

  # General / Sheet
  no-descending-specificity:
    - true
    - message: 禁止低优先级的选择器出现在高优先级的选择器之后
  no-duplicate-at-import-rules:
    - true
    - message: 禁止 @import 重复样式
  no-duplicate-selectors:
    - true
    - message: 在一个样式表中禁止出现重复的选择器
  no-extra-semicolons:
    - true
    - message: 禁止多余的分号
  max-line-length: 120

  # Scss
  scss/at-else-closing-brace-newline-after: always-last-in-chain
  scss/at-else-closing-brace-space-after: always-intermediate
  scss/at-else-empty-line-before: never
  scss/at-else-if-parentheses-space-before: null
  scss/at-extend-no-missing-placeholder: null
  scss/at-function-named-arguments: null
  scss/at-function-parentheses-space-before: null
  scss/at-function-pattern: null
  scss/at-if-closing-brace-newline-after: null
  scss/at-if-closing-brace-space-after: null
  scss/at-rule-no-unknown: true

  scss/double-slash-comment-empty-line-before:
    - null
    - message: 使用 // 注释之前必须有空行
  scss/double-slash-comment-whitespace-inside:
    - always
    - message: // 之后必须有一个空格
  scss/comment-no-loud:
    - true
    - message: 禁止使用 /* */ 注释

  # Order
  order/properties-alphabetical-order: true
